name: Deploy Anvil Privnode

on:
  push:
    paths:
      - 'testnets/**/chain.json'
      - 'mainnets/**/chain.json'
    branches:
      - main

jobs:
  deploy-privnode:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - region: asia-southeast
            env: staging
            base_url: https://api.anvil.asia-southeast.staging.initia.xyz
            firebase_secret: FIREBASE_SERVICE_ACCOUNT_STAGING
            api_key_secret: FIREBASE_API_KEY_STAGING
          - region: asia-southeast
            env: prod
            base_url: https://api.anvil.asia-southeast.initia.xyz
            firebase_secret: FIREBASE_SERVICE_ACCOUNT_PROD
            api_key_secret: FIREBASE_API_KEY_PROD
          - region: europe-west
            env: staging
            base_url: https://api.anvil.europe-west.staging.initia.xyz
            firebase_secret: FIREBASE_SERVICE_ACCOUNT_STAGING
            api_key_secret: FIREBASE_API_KEY_STAGING
          - region: europe-west
            env: prod
            base_url: https://api.anvil.europe-west.initia.xyz
            firebase_secret: FIREBASE_SERVICE_ACCOUNT_PROD
            api_key_secret: FIREBASE_API_KEY_PROD

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed chain.json files
        id: changed
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^testnets/.*/chain\.json$|^mainnets/.*/chain\.json$' || true)
          echo "files<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGED" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Setup Node.js
        if: steps.changed.outputs.files != ''
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        if: steps.changed.outputs.files != ''
        run: npm install firebase-admin axios

      - name: Write service account JSON
        if: steps.changed.outputs.files != ''
        working-directory: ./.github/workflows/utility
        run: echo '${{ secrets[matrix.firebase_secret] }}' > sa.json

      - name: Deploy Privnode in ${{ matrix.region }}
        if: steps.changed.outputs.files != ''
        env:
          FIREBASE_API_KEY: ${{ secrets[matrix.api_key_secret] }}
          BASE_URL: ${{ matrix.base_url }}
          REGION: ${{ matrix.region }}
          ENV_NAME: ${{ matrix.env }}
          CHANGED_FILES: ${{ steps.changed.outputs.files }}
        working-directory: ./.github/workflows/utility
        run: node deploy_privnode.js
